version: '3.8'

services:
  nginx:
    build:
      context: ./nginx/
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - static_files:/code/staticfiles/

  web:
    build: .
    expose:
      - 8000
    command: >
      sh -c "python manage.py migrate &&
             gunicorn rodeo_kg.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/usr/src/code/
      - static_files:/code/staticfiles/
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rodeo_db

volumes:
  static_files:
  postgres_data: