# Generated by Django 4.1.5 on 2023-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование новости')),
                ('body', models.TextField(max_length=255, verbose_name='Описание новости')),
                ('image', models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Изображение новости')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата создания новости')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
