# Generated by Django 4.1.5 on 2023-02-26 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_alter_champion_champion_alter_champion_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='Изображение в галерея')),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('bio', models.TextField(verbose_name='Описание')),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/', verbose_name='Фото участника')),
            ],
            options={
                'verbose_name': 'Участик турнира',
                'verbose_name_plural': 'Участники турниров',
            },
        ),
        migrations.AlterModelOptions(
            name='champion',
            options={'verbose_name': 'Чемпионы турниров', 'verbose_name_plural': 'Чемпион турнира'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'verbose_name': 'Турнир', 'verbose_name_plural': 'Турниры'},
        ),
        migrations.AlterField(
            model_name='champion',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champions', to='tournaments.tournament', verbose_name='Турнир'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateTimeField(verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='description',
            field=models.TextField(verbose_name='Описание турнира'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='image',
            field=models.ImageField(upload_to='tournament/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='title',
            field=models.CharField(max_length=256, verbose_name='Наименование турнира'),
        ),
        migrations.AlterField(
            model_name='champion',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='champions', to='tournaments.participant', verbose_name='Чемпион'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='tournaments.participant', verbose_name='Участники'),
        ),
    ]
