# Generated by Django 4.1.5 on 2023-03-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_gallery_options_gallery_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Изображение галереи', 'verbose_name_plural': 'Изображения галереи'},
        ),
    ]
