# Generated by Django 4.1.5 on 2023-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название билета?')),
                ('description', models.TextField(verbose_name='Описание билета')),
                ('price', models.PositiveIntegerField(verbose_name='Цена билета')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение мест на стадионе')),
            ],
        ),
    ]
