# Generated by Django 4.1.5 on 2023-02-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paybox', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Билет', 'verbose_name_plural': 'Билеты'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(upload_to='ticket/', verbose_name='Изображение мест на стадионе'),
        ),
    ]
